---
title: "local_tracker_api"
author: "Doug McNeall"
date: "8/17/2020"
output: html_document
---


## Introduction

Experiments with extracting coronavirus case data with the V1 API

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(jsonlite)
library(httr)

```


```{r}


get_api_data <- function(AREA_TYPE, AREA_NAME){
  
  endpoint <- "https://api.coronavirus.data.gov.uk/v1/data"
  
  
  # Create filters:
  
  filters <- c(
    
    sprintf("areaType=%s", AREA_TYPE),
    
    sprintf("areaName=%s", AREA_NAME)
    
  )
  
  
  # Create the structure as a list or a list of lists:
  
  structure <- list(
    
    date  = "date", 
    
    name  = "areaName", 
    
    code  = "areaCode", 
    
    dailyCases = "newCasesByPublishDate",
    
    cumulativeCases = "cumCasesByPublishDate",
    
    dailyDeaths = "newDeaths28DaysByPublishDate",
    
    cumulativeDeaths = "cumDeaths28DaysByPublishDate"
    
  )
  
  
  # The "httr::GET" method automatically encodes
  
  # the URL and its parameters:
  
  httr::GET(
    
    # Concatenate the filters vector using a semicolon.
    
    url = endpoint,
    
    
    # Convert the structure to JSON (ensure
    
    # that "auto_unbox" is set to TRUE).
    
    query = list(
      
      filters   = paste(filters, collapse = ";"),
      
      structure = jsonlite::toJSON(structure, auto_unbox = TRUE)
      
    ),
    
    
    # The API server will automatically reject any
    
    # requests that take longer than 10 seconds to
    
    # process.
    
    timeout(10)
    
  ) -> response
  
  
  # Handle errors:
  
  if (response$status_code >= 400) {
    
    err_msg = httr::http_status(response)
    
    stop(err_msg)
    
  }
  
  # Convert response from binary to JSON:
  
  json_text <- content(response, "text")
  
  data      <- jsonlite::fromJSON(json_text)
  
  
  # Store the encoded URL for inspection:
  
  url <- response$url
  
  return(list(url = url, data = data))
}


```


```{r}




dat <- get_api_data(AREA_TYPE = 'nation', AREA_NAME = 'England')
```

```{r}
plot_api_cases <- function(dat, region){
  
        da = seq(from = min(as.Date(dat$data$data$date)), to = max(as.Date(dat$data$data$date)), by = 7)

        par(las = 1, mar = c(2.5,4,5,1))
        plot(as.Date(dat$data$data$date), dat$data$data$dailyCases,
             xlab = '', ylab = 'cases', main = '',
             type = 'h', lwd = 5, col = 'skyblue2', bty = 'n', axes = FALSE,
             xlim = as.Date(c('2020-03-01', max(dat$data$data$date))))
        grid()
        
        axis.Date(1,at=da,labels=format(da,"%d %b"),las=1)
        axis(2)
        mtext(text = paste0('Daily lab-confirmed Covid-19 cases in ', region), side = 3, line = .5, adj = 0, cex = 1.5)
  
}
```



```{r}

plot_api_cases(get_api_data(AREA_TYPE = 'ltla', AREA_NAME = 'Exeter'), 'Exeter') 

```











