---
title: "London Sensitivity Analysis example"
author: "Doug McNeall"
date: "11/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## FAST99 Sensitivity Analysis, London 


```{r}
library(emtools)
library(viztools)
library(imptools)
library(sensitivity)
library(tidyverse)
```


```{r}
bp_convert <- function(fastmodel){
  # get the FAST summary into an easier format for barplot
  fast_summ <- print(fastmodel)
  fast_diff <- fast_summ[ ,2] - fast_summ[ ,1]
  fast_bp <- t(cbind(fast_summ[ ,1], fast_diff))
  fast_bp
}
```


```{r}
dat <- read.csv('../data/regionLondonW12age8.csv')
```


Removea clear outlier in the data
```{r}
mx <- which.max(dat$deaths)
dat_trunc <- dat[-mx, ]

```


```{r}
n <- nrow(dat_trunc)
p <- ncol(dat_trunc) - 1

X <- dat_trunc[, 1:p]
y <- c(dat_trunc['deaths'], recursive = TRUE)

X_norm <- normalize(X)




```

```{r, fig.width = 8, fig.height = 12}

par(mfrow = c(5,3 ))
for(i in 1:ncol(X_norm)){
  
  plot(X_norm[, i], log(y), xlab = colnames(X_norm)[i] )
}
```




```{r, fig.width = 6, fig.height = 10}
fit <- km(~., design = X_norm, response = log(y), control = list(trace = FALSE))

plot(fit)
```


This is weird - it seems to be vastly overinflating the influence of eta, given the lack of signal in the marginal plot, and I'm struggling to see why.

It looks like the emulator has fit something weird to eta.
```{r}

# Generate a design for the FAST99 analysis
X_fast <- fast99(model = NULL, factors = colnames(X_norm), n = 3000,
                 q = "qunif", q.arg = list(min = 0, max = 1))


# Predict the response at the FAST99 design points using the emulator
pred_fast = predict(fit, newdata = X_fast$X, type = 'UK')

# Calculate the sensitivity indices
fast_tell <- tell(X_fast, pred_fast$mean)

bp_convert <- function(fastmodel){
  # get the FAST summary into an easier format for barplot
  fast_summ <- print(fastmodel)
  fast_diff <- fast_summ[ ,2] - fast_summ[ ,1]
  fast_bp <- t(cbind(fast_summ[ ,1], fast_diff))
  fast_bp
}

par(las = 2, mar = c(9,5,3,2))
barplot(bp_convert(fast_tell), col = c('skyblue', 'grey'), 
        ylab = 'relative sensitivity', 
	main = 'FAST99 Sensitivity')


```



```{r}

oaatLinePlot <- function (X_oaat, y_oaat_mean, y_oaat_sd, n_oaat, nr, nc, linecol = "black", 
    shadecol = "grey", ...) 
{
    col.transp <- adjustcolor(shadecol, alpha = 0.5)
    par(mfrow = c(nr, nc), oma = c(0.1, 0.1, 3, 0.1), mar = c(2, 
        2, 3, 1))
    for (i in 1:ncol(X_oaat)) {
        ix <- seq(from = ((i * n_oaat) - (n_oaat - 1)), to = (i * 
            n_oaat), by = 1)
        plot(X_oaat[ix, i], y_oaat_mean[ix], xlim = c(0, 1), 
            ylim = range(c(y_oaat_mean + (2 * y_oaat_sd), y_oaat_mean - 
                (2 * y_oaat_sd))), xlab = colnames(X_oaat)[i], 
            type = "n", bty = "n", ...)
        polygon(x = c(X_oaat[ix, i], rev(X_oaat[ix, i])), y = c(y_oaat_mean[ix] - 
            (2 * y_oaat_sd[ix]), rev(y_oaat_mean[ix] + (2 * y_oaat_sd[ix]))), 
            col = col.transp, border = col.transp)
        lines(X_oaat[ix, i], y_oaat_mean[ix], xlim = c(0, 1), 
            lty = "solid", col = linecol)
        mtext(colnames(X_oaat)[i], side = 3, line = 0.5)
    }
    mtext("One-at-a-time sensitivity", side = 3, outer = TRUE, 
        cex = 1.5)
}

```

```{r, fig.width = 8, fig.height = 12}

X_oaat <- oaat_design(X_norm, n = 21, med = TRUE) 

pred_oaat <- predict(fit, newdata = X_oaat, type = 'UK')
y_oaat_mean <- pred_oaat$mean
y_oaat_sd <- pred_oaat$sd

oaatLinePlot(X_oaat, y_oaat_mean = y_oaat_mean, y_oaat_sd = y_oaat_sd, n_oaat = 21, nr = 5, nc = 3 )

```


```{r}

lmfit <- lm(log(y) ~ X_norm)

summary(lmfit)


```


