---
 title: "readRegionDeaths"
author: "Doug McNeall"
date: "5/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
```



```{r}
# Regions, e.g. South West, North East, ...
regions <- paste("E1200000", 1:9, sep = "")

# files with deaths for each regions by age bands
fl0 <- "https://api.coronavirus.data.gov.uk/v2/data?areaType=region&areaCode=E12000001&metric=newDeaths28DaysByDeathDateAgeDemographics&format=csv"
```


## put into list data for each region

```{r}

if(file.exists('RegionDeaths0_20210510.rds')){
  
  dat <- readRDS("RegionDeaths0_20210510.rds")
  
} else
  {
dat <- lapply(regions, function(x) read.csv(gsub(regions[1], x, fl0)))
names(dat) <- regions

# bind list into single data.frame

saveRDS(dat, "RegionDeaths0_20210510.rds")
}

dat <- do.call(rbind, dat)
```


```{r}
# ages we want (to avoid overlapping age bands)
ages <- c("00_04", "05_09", "10_14", "15_19", "20_24", "25_29", "30_34", 
  "35_39", "40_44", "45_49", "50_54", "55_59", "60_64", "65_69", 
  "70_74", "75_79", "80_84", "85_89", "90+")
dat <- subset(dat, age %in% ages)
# dates
dates <- sort(unique(dat$date))

# set as factors, to make life easy for putting into an array
dat$age <- factor(dat$age, levels = ages)
dat$date <- factor(dat$date, levels = dates)
dat$areaCode <- factor(dat$areaCode, levels = regions)

# then put into array in form dates x regions x ages
# (maybe not the most logical order: use aperm to change)
dimnames <- list(date = dates, regin = regions, age = ages)
arr <- array(0L, dim = sapply(dimnames, length), dimnames = dimnames)
ind <- cbind(as.integer(dat$date), as.integer(dat$areaCode), as.integer(dat$age))
arr[ind] <- dat$deaths

saveRDS(arr, "RegionDeaths_20210510.rds")

```


## Visualise the deaths data

```{r}

# this produces region in rows and age bands in the columns (i.e. sums over all time)
test <- apply(arr, c(2,3), sum)


```


# Hovmeuller plot by age band
```{r, fig.width = 9, fig.height = 7}
hm <- apply(arr, c(1,3), sum)

nr <- nrow(hm)
nc <- ncol(hm)

par(mar = c(8, 4, 2, 1))
image(hm, axes = FALSE)
tax <- seq(from = 1/nr, to = 1, by = 1/nr)
aax <- seq(from = 1/nc, to = 1, by = 1/nc)

axis(1, at = tax, labels = rownames(hm),las = 2, cex = 0.3)
axis(2, at = aax, labels = colnames(hm), las = 1, cex = 0.3)


```





```{r}


library(lubridate)
deaths_ts <- apply(arr, 1, sum)

deaths_ts_df <- tibble(time = ymd(names(deaths_ts)), deaths = deaths_ts)

p  <- ggplot(deaths_ts_df, aes(x=time, y=deaths)) +
  geom_line() + 
  xlab("")
p

```


```{r}

date <- ymd(rownames(arr))
           
rt <- as_tibble(apply(arr, c(1,2), sum))

rtd <- add_column(rt, date)

#tax <- ymd(rownames(rt))

ggplot(rtd) +
  
  geom_line(data = rtd, aes(x = date, y = E12000001), colour = 'red' ) +
  geom_line(data = rtd, aes(x = date, y = E12000002), colour = 'blue' )

```



```{r}






```


```{r}
# load in population by region and age data
# from here
# https://www.ons.gov.uk/peoplepopulationandcommunity/populationandmigration/populationestimates/datasets/populationestimatesforukenglandandwalesscotlandandnorthernireland
# and then butchered into a csv
pop0 <- read.csv("ukmidyearestimates20192020ladcodes_v2.csv")
# get just region data
pop0 <- subset(pop0, Geography == "Region")
# put into age bands above (could be done less manually)
band <- rep(seq_along(ages[-1]), each = 5)
band <- c(band, max(band) + 1)
# aggregate over bands
pop <- as.data.frame(t(apply(pop0[, substr(names(pop0), 1, 1) == "X"], 1, tapply, band, sum)))
names(pop) <- ages
# and then save
saveRDS(pop, "RegionPop_20210510.rds")


```

```{r}


regionNames
```



```{r}

#deathsPerRegion <- rt

deathsPerRegion <- rt %>% 
  as_tibble() %>%
  add_column(date)


deathsPerRegion %>%
  pivot_longer(pop0$Code) %>%
  ggplot((aes(x = date, y = value, colour = name))) +
  geom_line() +
  facet_wrap(~name)
```



# Death rates in each region

```{r}
popPerRegion <- apply(pop, 1, sum)

deathsPerRegionNorm <- sweep(rt, STATS = popPerRegion, MARGIN = 2, FUN = '/') * 100000 

deathsPerRegionNormDate <- as_tibble(deathsPerRegionNorm)

deathsPerRegionNormDate <- add_column(deathsPerRegionNormDate, date)


ggplot(deathsPerRegionNormDate ) +
  
  geom_line(data = deathsPerRegionNormDate, aes(x = date, y = E12000001), colour = 'red' ) +
  geom_line(data = deathsPerRegionNormDate, aes(x = date, y = E12000002), colour = 'blue' ) +
  geom_line(data = deathsPerRegionNormDate, aes(x = date, y = E12000003), colour = 'pink') +
  geom_line(data = deathsPerRegionNormDate, aes(x = date, y = E12000004), colour = 'gold' ) +
  geom_line(data = deathsPerRegionNormDate, aes(x = date, y = E12000005), colour = 'black' ) +
  geom_line(data = deathsPerRegionNormDate, aes(x = date, y = E12000006), colour = 'green' ) +
  geom_line(data = deathsPerRegionNormDate, aes(x = date, y = E12000007), colour = 'tomato2' ) +
  geom_line(data = deathsPerRegionNormDate, aes(x = date, y = E12000008), colour = 'skyblue2' ) +
  geom_line(data = deathsPerRegionNormDate, aes(x = date, y = E12000009), colour = 'purple' )


```


```{r, fig.width = 12, fig.height = 8}

deathsPerRegionNormDateName <- deathsPerRegionNormDate

colnames(deathsPerRegionNormDateName)[1:9] <- as.character(pop0$Name)

deathsPerRegionNormDateName %>%
  
  pivot_longer(cols = pop0$Name) %>%
  
  ggplot(aes(x = date, y = value, colour = name)) +
  geom_line() +
  facet_wrap(~name)

```

# Deaths that occurred by lockdown in each region

```{r}

deathsPerRegionPreLockdown <- deathsPerRegion %>%
  filter(date < "2020-03-22")

colnames(deathsPerRegionPreLockdown)[1:9] <- as.character(pop0$Name)


```

```{r}

deathsPerRegionPreLockdown %>%
  pivot_longer(cols = pop0$Name) %>%
  ggplot(aes(x = date, y = value, colour = name)) +
  geom_line() +
  facet_wrap(~name)
```

```{r}
deathsPerRegionPreLockdownSum <- apply(deathsPerRegionPreLockdown[,1:9], MARGIN = 2, FUN = sum)

deathsPerRegionPreLockdownSum


```
## How do the regional proportions change as we go into lockdown?
```{r}
# James has data from before 21st March

deathsPerRegionPreLockdown <- deathsPerRegion %>%
  filter(date < "2020-03-22")

colnames(deathsPerRegionPreLockdown)[1:9] <- as.character(pop0$Name)
deathsPerRegionPreLockdownSum <- apply(deathsPerRegionPreLockdown[,1:9], MARGIN = 2, FUN = sum)
(deathsPerRegionPreLockdownSum /  sum(deathsPerRegionPreLockdownSum) ) * 100

```

```{r}

(deathsPerRegionPreLockdownSum /  sum(deathsPerRegionPreLockdownSum) ) * 100

```





